"use client";

import { useEffect, useState } from "react";
import { Sparkles, X } from "lucide-react";

/**
 * The one AI surface in the product. It reads the document that is already open
 * and returns a summary — no chat, no agent, no prompt box. A single action with
 * a visible loading state and a real error path was worth more than a broader
 * feature that half worked.
 */
export function SummaryPanel({
  documentId,
  title,
  onClose,
}: {
  documentId: string;
  title: string;
  onClose: () => void;
}) {
  const [summary, setSummary] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [truncated, setTruncated] = useState(false);

  useEffect(() => {
    let cancelled = false;

    (async () => {
      try {
        const res = await fetch(`/api/documents/${documentId}/summarize`, {
          method: "POST",
        });
        const body = await res.json();
        if (cancelled) return;

        if (!res.ok) setError(body.error ?? "Could not summarise this document.");
        else {
          setSummary(body.summary);
          setTruncated(Boolean(body.truncated));
        }
      } catch {
        if (!cancelled) setError("Network error — could not reach the server.");
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [documentId]);

  useEffect(() => {
    function onEsc(e: KeyboardEvent) {
      if (e.key === "Escape") onClose();
    }
    document.addEventListener("keydown", onEsc);
    return () => document.removeEventListener("keydown", onEsc);
  }, [onClose]);

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-ink-900/30 p-4 backdrop-blur-sm"
      onMouseDown={(e) => e.target === e.currentTarget && onClose()}
    >
      <div
        role="dialog"
        aria-modal="true"
        aria-labelledby="summary-title"
        className="surface-raised w-full max-w-lg rounded-2xl p-5 rise-in"
      >
        <div className="mb-4 flex items-start justify-between gap-3">
          <div className="min-w-0">
            <h2
              id="summary-title"
              className="flex items-center gap-1.5 text-base font-semibold text-ink-900"
            >
              <Sparkles className="h-4 w-4 text-accent" />
              Summary
            </h2>
            <p className="mt-0.5 truncate text-xs text-ink-500">{title}</p>
          </div>
          <button
            type="button"
            onClick={onClose}
            aria-label="Close"
            className="rounded-lg p-1 text-ink-400 transition hover:bg-ink-100 hover:text-ink-700"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {loading && (
          <div className="space-y-2.5 py-2" aria-live="polite" aria-busy="true">
            <span className="sr-only">Generating summary…</span>
            {[100, 92, 96, 70].map((w, i) => (
              <div
                key={i}
                style={{ width: `${w}%`, animationDelay: `${i * 90}ms` }}
                className="h-3 animate-pulse rounded bg-ink-100"
              />
            ))}
          </div>
        )}

        {error && (
          <p
            role="alert"
            className="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2.5 text-sm text-amber-800"
          >
            {error}
          </p>
        )}

        {summary && (
          <div className="whitespace-pre-wrap text-sm leading-relaxed text-ink-700">
            {summary}
          </div>
        )}

        {(summary || error) && (
          <p className="mt-4 border-t border-ink-100 pt-3 text-[11px] text-ink-400">
            {truncated
              ? "Generated by Gemini from the first ~24,000 characters. "
              : "Generated by Gemini. "}
            Summaries can be wrong — check them against the document.
          </p>
        )}
      </div>
    </div>
  );
}
